name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v -coverprofile=coverage.out -json ./... | tee test-report.json

      - name: Convert test report to JUnit XML
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'test-report.json'
          output: 'junit.xml'

      - name: Test Reporter
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Go Tests
          path: junit.xml
          reporter: java-junit
